### ISSUE TITLE
I can translate to UA

### ISSUE THREAD

**Issue by petrussola** [fuzzbuck/uatranshelp#2]
Is somebody helping with translation to Ukrainian? Not a native speaker but can do a quick Google translate to get you going. My Ukrainian wife is attending a protest at the moment here in Ireland, I will ask her to proof read but at least you will have sth to get going asap.

**Comment by fuzzbuck** [comment]
> Is somebody helping with translation to Ukrainian? Not a native speaker but can do a quick Google translate to get you going. My Ukrainian wife is attending a protest at the moment here in Ireland, I will ask her to proof read but at least you will have sth to get going asap.

Currently there is 0 progress on Ukrainian so that would be great!

Make sure to read the translation guidelines (README.md), try to keep the text style & length similar to base (english) locale.

**Comment by fuzzbuck** [comment]
Hi, are you still looking to translate?

**Comment by petrussola** [comment]
I am! Got tangled with something else today. If you have someone to work on it tomorrow, please pass it on. Otherwise, I will give it a try tomorrow evening. Sorry about the delay 🙏

**Comment by fuzzbuck** [comment]
ukrainian.json has been per-emptively translated w/ google translate, but still needs proofreading & verification.
Much appreciated if you would do that

**Comment by petrussola** [comment]
Done! My wife just proof read it. See [here](https://github.com/fuzzbuck/uatranshelp/compare/dev...petrussola:patch-1). Not familiar with your branch schema, so I will leave as is but can open PR if needed.

**Comment by fuzzbuck** [comment]
Much appreciated! I'll look over and push the commits myself as necessary
